version: '3'
services:

  nginx:
    restart: on-failure
    build:
      context: ./
      dockerfile: nginx/nginx.docker
    volumes:
      - ./app/public/:/var/www
    ports:
      - "8555:80"
    depends_on:
      - app
      - npm
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "5"

  app:
    restart: on-failure
    container_name: numberlookup_app
    build:
      context: ./app/
      dockerfile: deployment/app.docker
    volumes:
      - ./app/:/usr/src/app
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "5"

  npm:
    restart: on-failure
    container_name: numberlookup_npm
    build:
      context: ./app/public
      dockerfile: npm.docker
    volumes:
      - ./app/public/:/usr/src/app
      - /usr/src/app/node_modules
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "5"